//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFMElectronique.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFMElectronique.Views.Shared.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appelez nous 222-555-6666.
        /// </summary>
        public static string CallUs {
            get {
                return ResourceManager.GetString("CallUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer votre mot de passe.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Changer vos informations].
        /// </summary>
        public static string ChangeYourInformations {
            get {
                return ResourceManager.GetString("ChangeYourInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Changer votre mot de passe].
        /// </summary>
        public static string ChangeYourPassword {
            get {
                return ResourceManager.GetString("ChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMFElectronique..
        /// </summary>
        public static string contactLine01 {
            get {
                return ResourceManager.GetString("contactLine01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3000 Avenue Boullé.
        /// </summary>
        public static string contactLine02 {
            get {
                return ResourceManager.GetString("contactLine02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint-Hyacinthe.
        /// </summary>
        public static string contactLine03 {
            get {
                return ResourceManager.GetString("contactLine03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Québec J2S 1H9.
        /// </summary>
        public static string contactLine04 {
            get {
                return ResourceManager.GetString("contactLine04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (514) 875-4445.
        /// </summary>
        public static string contactLine05 {
            get {
                return ResourceManager.GetString("contactLine05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string contactLine06 {
            get {
                return ResourceManager.GetString("contactLine06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous contacter.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur..
        /// </summary>
        public static string Error01 {
            get {
                return ResourceManager.GetString("Error01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors du traitement de votre demande..
        /// </summary>
        public static string Error02 {
            get {
                return ResourceManager.GetString("Error02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonjour .
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venez nous rejoindre à .
        /// </summary>
        public static string infoLine01 {
            get {
                return ResourceManager.GetString("infoLine01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint-Hyacinthe!.
        /// </summary>
        public static string infoLine02 {
            get {
                return ResourceManager.GetString("infoLine02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous avons un excellent.
        /// </summary>
        public static string infoLine03 {
            get {
                return ResourceManager.GetString("infoLine03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service de livraison.
        /// </summary>
        public static string infoLine04 {
            get {
                return ResourceManager.GetString("infoLine04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to et nous acceptons.
        /// </summary>
        public static string infoLine05 {
            get {
                return ResourceManager.GetString("infoLine05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to les enveloppes brunes!.
        /// </summary>
        public static string infoLine06 {
            get {
                return ResourceManager.GetString("infoLine06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verrouillé..
        /// </summary>
        public static string Lockout01 {
            get {
                return ResourceManager.GetString("Lockout01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce compte a été bloqué , se il vous plaît réessayer plus tard..
        /// </summary>
        public static string Lockout02 {
            get {
                return ResourceManager.GetString("Lockout02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se connecter.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se déconnecter.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphones.
        /// </summary>
        public static string Phones {
            get {
                return ResourceManager.GetString("Phones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achats.
        /// </summary>
        public static string Purchases {
            get {
                return ResourceManager.GetString("Purchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;enregistrer.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livraison rapide!.
        /// </summary>
        public static string ShippingText {
            get {
                return ResourceManager.GetString("ShippingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablettes.
        /// </summary>
        public static string Tablets {
            get {
                return ResourceManager.GetString("Tablets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montres.
        /// </summary>
        public static string Watches {
            get {
                return ResourceManager.GetString("Watches", resourceCulture);
            }
        }
    }
}
