//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFMElectronique.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFMElectronique.Views.Shared.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonjour .
        /// </summary>
        public static string Allo {
            get {
                return ResourceManager.GetString("Allo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Appelez nous! Sans frais:.
        /// </summary>
        public static string AppelezNous {
            get {
                return ResourceManager.GetString("AppelezNous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Panier.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier vos informations.
        /// </summary>
        public static string ChangeYourInformations {
            get {
                return ResourceManager.GetString("ChangeYourInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier votre mot de passe.
        /// </summary>
        public static string ChangeYourPassword {
            get {
                return ResourceManager.GetString("ChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contactez nous.
        /// </summary>
        public static string ContactezNous {
            get {
                return ResourceManager.GetString("ContactezNous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 500 Lorem Ipsum Dolor Sit,.
        /// </summary>
        public static string contactLine01 {
            get {
                return ResourceManager.GetString("contactLine01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 22-56-2-9 Sit Amet, Lorem,.
        /// </summary>
        public static string contactLine02 {
            get {
                return ResourceManager.GetString("contactLine02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à USA.
        /// </summary>
        public static string contactLine03 {
            get {
                return ResourceManager.GetString("contactLine03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Téléphone:(00) 222 666 444.
        /// </summary>
        public static string contactLine04 {
            get {
                return ResourceManager.GetString("contactLine04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fax: (000) 000 00 00 0.
        /// </summary>
        public static string contactLine05 {
            get {
                return ResourceManager.GetString("contactLine05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Courriel: email@leoshop.com.
        /// </summary>
        public static string contactLine06 {
            get {
                return ResourceManager.GetString("contactLine06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accueil.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à des trucs.
        /// </summary>
        public static string infoLine01 {
            get {
                return ResourceManager.GetString("infoLine01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à des trucs.
        /// </summary>
        public static string infoLine02 {
            get {
                return ResourceManager.GetString("infoLine02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à des trucs.
        /// </summary>
        public static string infoLine03 {
            get {
                return ResourceManager.GetString("infoLine03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à des trucs.
        /// </summary>
        public static string infoLine04 {
            get {
                return ResourceManager.GetString("infoLine04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à des trucs.
        /// </summary>
        public static string infoLine05 {
            get {
                return ResourceManager.GetString("infoLine05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à des trucs.
        /// </summary>
        public static string infoLine06 {
            get {
                return ResourceManager.GetString("infoLine06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TODO?.
        /// </summary>
        public static string InfoShipping {
            get {
                return ResourceManager.GetString("InfoShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se connecter.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se déconnecter.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Téléphones.
        /// </summary>
        public static string Phones {
            get {
                return ResourceManager.GetString("Phones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Achats.
        /// </summary>
        public static string Purchases {
            get {
                return ResourceManager.GetString("Purchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer un compte.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tablettes.
        /// </summary>
        public static string Tablets {
            get {
                return ResourceManager.GetString("Tablets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montres.
        /// </summary>
        public static string Watches {
            get {
                return ResourceManager.GetString("Watches", resourceCulture);
            }
        }
    }
}
